### ISSUE TITLE
Bug: "Proposal Created . Ago" Date on Dashboard Shows Unknown

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#1005]
This issue could possibly be fixed in the Feed PR #1004 if it is a small issue. Otherwise I will create a separate PR.

 ![Image](https://github.com/user-attachments/assets/9935a636-9ffa-47ea-b19d-0bbcb624499c)

**Comment by ori-near** [comment]
Thomas said the issue resolved on its own.
