### ISSUE TITLE
allow communities to create their own teams and their own tags for kanban score

### ISSUE THREAD

**Issue by nearbuild** [NEAR-DevHub/neardevhub-bos#120]
**Is your feature request related to a problem? Please describe.**
Right now entities like NEAR Digital Collective, Marketing DAO want to use gigs board but it gets cluttered
**Describe the solution you'd like**
Allow different entities to have their own teams that can put specific tags like #marketing-dao, #ndc for bounty boards in the kanban view.
**Describe alternatives you've considered**
Forking gigs board, using other bounty items.
**Additional context**
Very timely

**Comment by elliotBraem** [comment]
I would like to work on this
