### ISSUE TITLE
Ability to filter based on highest sponsorships

### ISSUE THREAD

**Issue by nearbuild** [NEAR-DevHub/neardevhub-bos#121]
**Is your feature request related to a problem? Please describe.**
Similar to root.near original IdeasList where Sponsored tasks are prioritized to top. Simply want to filter by biggest sponsored tasks. Right now developers are looking for opportunities, would be great to see the ones that offer the most monetary value

**Describe the solution you'd like**

**Describe alternatives you've considered**
Add fiilter by sponsorship low-high and high to love.

**Comment by ailisp** [comment]
Should be add to the new sponsorship epic. From technical side, it's possible to achieve this query this with current indexer.
