### ISSUE TITLE
Make Sponsorships and Attestations given to the top-level posts visually prominent

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/neardevhub-bos#130]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when reading the Feed and unable to quickly understand if the idea/initiative is already reviewed / funded / rejected.

Take this "Solution: Request to subsidize gas fee for Electron bridge"

<img width="1335" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/8dad693d-c7f1-4896-86b9-abfbbc73a8bc">

The only hint right now is the number of replies, which is easy to miss at a glance, and even after you expand them, you need to scan through to find attestations and sponsorship.

**Describe the solution you'd like**

I don't have great UI suggestions. I would consider adding some clear indicators about the number of attestations and sponsorships next to or over the 🚀 icon next to "Solution" or making it even more prominent.

**Describe alternatives you've considered**

An alternative would be to revamp the feed and display only sponsored initiatives. Though, it makes it harder to discover new ideas as they will need to be displayed under a separate tab.

**Additional context**

I hope someone with better UI taste can some up with the exact solution.

**Comment by Rishabhraghwendra18** [comment]
Hi @frol, Idk whether this issue is still open.
We can also have the labels (like reviewed/funded/rejected) next to tags in different colors, for example yellow, orange, or red to make posts visually prominent. 

Also, it can help us to filter out posts based on reviewed/funded/rejected in the future.

**Comment by ailisp** [comment]
Update estimation, leaving 1 day for design and 1 day for implementation
