### ISSUE TITLE
[Communities] Archive old boards page after new boards is launched

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#208]
After we launch the new communities board https://github.com/near/neardevhub-widgets/issues/156, we need to create a new Funding page under the DevHub community and remove the old pages.

**Acceptance Criteria**
- Create a new Funding Board under DevHub community. It should have the same setup as https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Boards?selectedBoardId=funding
- Redirect the old Funding Board URL (https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Boards?selectedBoardId=funding) to the new DevHub Community Funding Board
- Delete this page: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Boards

**Comment by ailisp** [comment]
We would need a design for the new board
