### ISSUE TITLE
Improve the post editing experience

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#240]
**Problem**
We've received feedback that the post editing experience is unclear. Issues:
1. **Confusing Dropdown:** The dropdown when clicking "edit post" is unclear. It intends to allow users to change the post type and proceed with the editing experience.
2. **Editor Popup:** When users click on any of the edit options in the dropdown menu, an editor appears below the the post, which sometimes falls below the bottom of the screen. So users might miss this and think the button isn't working.
3. **Multiple Versions:** Once users enter edit mode, they see 3 versions of the post on the screen: The original published one at the top, the editor in the middle, and the preview on the bottom. This can be frustrating, as there are multiple versions of the post.

**Solution**
[Need to explore solution here. We ideally need to streamline the editing process without relying on a dropdown for post type changes. Additionally, the editor should be fully visible on the screen when entering edit mode. Lastly, we should present a clear and organized layout without overwhelming users with multiple versions of the post at once.]

**Comment by ailisp** [comment]
I don't have a very good solution here, I think this need a lot of thinking on the UX. Edit as "XXX" does not make sense for maybe 90% of use where user just want to edit it as current type. There can be 10% of case where the previously select post type is not right, and user or moderator may want to change it.
