### ISSUE TITLE
Implement sort by hottest

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-bos#328]
Sort by hottest is lost in server side search. Implement that in QueryAPI side then integrate to frontend

**Comment by ailisp** [comment]
Back to work on this issue today. I was prioritize #348 and just get it fixed.

**Comment by ori-near** [comment]
@ailisp This ticket has been in progress for a while. Are you actually working on it? I'm moving it to backlog for now, but please update.
