### ISSUE TITLE
Refactor directory structure for pages

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/neardevhub-bos#350]
Rather than using app as a root where navigation works like:

```
devhub.near/widget/app?page=home
devhub.near/widget/app?page=feed
devhub.near/widget/app?page=community
```

We will want to replace this with:

```
devhub.near/widget/dh.home
devhub.near/widget/dh.feed
devhub.near/widget/dh.community
```

This can be widgets that handle the page route for us, such as:

devhub.near/widget/dh.blog:

```javascript
return (
  <Widget
    src={"${REPL_DEVHUB}/widget/app"}
    props={{ page: "blog", ...props }}
  />
);
```

## Considerations

Once a user navigates to a page and then clicks a link inside, they will navigate to /app?page= again. Otherwise we update the <Link to= to reflect the new pages

**Comment by itexpert120** [comment]
We are getting rid of app?

**Comment by jaswinder6991** [comment]
@elliotBraem would you help with this?

**Comment by ori-near** [comment]
Hi @elliotBraem – Can you please add more details to this ticket? Also estimated size? Can we move this to the backlog?

**Comment by Tguntenaar** [comment]
I will pick this up

**Comment by Tguntenaar** [comment]
This was put in the icebox
