### ISSUE TITLE
Metadata for individual pages like Blogs etc to improve shareability of links on social apps.

### ISSUE THREAD

**Issue by jaswinder6991** [NEAR-DevHub/neardevhub-bos#450]
**Is your feature request related to a problem? Please describe.**
Improve shareability of individual subpages on the DevHub app. 

**Describe the solution you'd like**
We need to add metadata for different pages in the Devhub app so that we when share individual page links like a post, a community, a blog etc, we get good social cards on the site(example twitter) we are sharing a link. 

**Screenshot**
Example social card for the homepage on Telegram
<img width="271" alt="Screenshot 2023-11-08 at 11 03 11 PM" src="https://github.com/near/neardevhub-widgets/assets/12672862/f60a2b22-ee22-4772-98f1-6c78cd830048">

**Comment by ori-near** [comment]
Hi @jaswinder6991 can you please flesh out this ticket with a solution?

**Comment by ori-near** [comment]
Solving this in https://github.com/NEAR-DevHub/neardevhub-bos/issues/724
