### ISSUE TITLE
Link not visible on Github page of DevHub Test Area

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-bos#499]
Link to the [DevHub Test Area](https://near.social/devhub.near/widget/app?page=community&handle=devhub-test&tab=Github)

<img width="1379" alt="image" src="https://github.com/near/neardevhub-widgets/assets/100185149/d0a0b304-2cdf-42fd-8828-264a1e28fefb">

**Comment by ailisp** [comment]
Hi @Megha-Dev-19 Could you elaborate this a little bit? I don't understand what's the issue

**Comment by Megha-Dev-19** [comment]
Hey @ailisp in the image you can see there is a button in the right corner “Copy Link”, but I don’t see any link in the left which I would want to copy.
So is there a link hidden in the black bg.?

**Comment by Tguntenaar** [comment]
I believe it is supposed to be this way. You copy the link of the current page which is shown in the url bar.

**Comment by Megha-Dev-19** [comment]
oh is it, then I think we should improve the UI, since I have mostly seen the "Copy Link" btn adjacent to a link, or may be we can rename it to "Copy current page URL".
if not we can close the issue also, fine by me
Thanks
