### ISSUE TITLE
Execution error in github tab for devhub test community

### ISSUE THREAD

**Issue by itexpert120** [NEAR-DevHub/neardevhub-bos#539]
![image](https://github.com/near/neardevhub-widgets/assets/46527178/0646a33e-4327-4f36-9cd4-eb3e5d0863f7)

**Comment by Tguntenaar** [comment]
Hi @Megha-Dev-19, there is no linked PR on this issue. They will automatically link if you put “\_Resolves #XX\_” with the issue number in the PR.
