### ISSUE TITLE
Telegram is expecting a sequence rather than String

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/neardevhub-bos#544]
**Describe the bug**

When updating a community's Telegram handle, we're getting this error:

```json
{"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error(\"invalid type: string \\\"NEARSecurity\\\", expected a sequence\", line: 1, column: 522)', src/lib.rs:49:1"}}
```

**To Reproduce**
1. Go to a community
2. Click on community configuration
3. Edit a telegram handle
4. Submit

**Expected behavior**

Behind the scenes, the inputted Telegram handle is supposed to be within an array before making the call to contract.

### Correction

After talking with @ori-near , we should instead be modifying the community to only allow one Telegram handle. Creating a story on contract side to reflect this change

**Comment by elliotBraem** [comment]
An issue has been created on the contract side to fix this: [near/neardevhub-contract#76](https://github.com/near/neardevhub-contract/issues/76)

Then these changes will need to be reflected on the UI

**Comment by Tguntenaar** [comment]
I will pick this up, since I'm currently blocked on issue 456.

**Comment by Tguntenaar** [comment]
@ailisp could you review PR 77 in the neardevhub-contract repo?
