### ISSUE TITLE
 Allow description for blog tab

### ISSUE THREAD

**Issue by PiVortex** [NEAR-DevHub/neardevhub-bos#562]
Is your feature request related to a problem? Please describe.
When adding a blogs tab to a community page you are unable to add a description for the whole tab, you can add information for each blog but not the whole tab.
image

Describe the solution you'd like
Introduce a standard text box or markdown text box that allows the author of the tab to write what the blogs are used for and how they can submit a blog.

**Comment by ori-near** [comment]
Thanks for filing this @PiVortex. I think right now we're missing a "Blog Settings/Configuration" section for admins. It would be nice to create a section for that where we can incorporate this functionality, among others (see https://github.com/NEAR-DevHub/neardevhub-bos/issues/599).

CC: @elliotBraem.

**Comment by ailisp** [comment]
Hi @PiVortex , can you clarify a little bit, maybe a scratch of how the title/subtitle should look like on the blogs page? Should it include only title/subtitle or can be arbitrary bos widget?

**Comment by ori-near** [comment]
Closing this ticket, as I incorporate it instead into: https://github.com/NEAR-DevHub/neardevhub-bos/issues/599
