### ISSUE TITLE
Separate Instances of Blog Widget for Each Page

### ISSUE THREAD

**Issue by victorchimakanu** [NEAR-DevHub/neardevhub-bos#568]
## Feature Request:
I would like to request the ability to create separate instances of a blog widget for each page on DevHub. Currently, when using the blog widget, any information stored is pulled and displayed on every page. However, for better customization, it would be beneficial to have the option to create unique instances of the blog widget for each page.

## Reasons:

1. As a user, I want to have distinct blog content on different pages of my DevHub blog.
2. Having separate instances of the blog widget for each page would allow me to tailor the content based on the context of each page.

**Comment by ori-near** [comment]
Thanks for filing this @victorchimakanu. I agree that if a user creates multiple instances of the blog widget, the content type that they create within it should be separate. For example, suppose a user wants to use the blog widget to create a Recent Calls tab. And then they want a separate blog widget to track updates specific to one project. Right now any blog posts they create will appear in both.
