### ISSUE TITLE
Labels bug

### ISSUE THREAD

**Issue by PiVortex** [NEAR-DevHub/neardevhub-bos#576]
**Describe the bug**
There seem to be multiple bugs with labels on both ideas and solutions for posts.
1) Adding a label, and 2) posting from a community, I have both seen errors.

**To Reproduce**
1) When creating an idea or solution post I add a label, the label will not show in the labels box but it will be posted with that label. I cannot add two labels, it will remove the previous one.

2) When posting from a community it automatically shows the label in the labels box but it will not actually be posted with the label

**Expected behavior**

1) All labels should show in the label box and be attached to the post when inserted.

2) When posting from a community the community's respective label should automatically be added.

**Screenshots**

**Desktop (please complete the following information):**
Chrome
Windows 10

**Comment by itexpert120** [comment]
I'll work on this
