### ISSUE TITLE
Homepage /get support section – Fix Office Hours "Book a meeting" link

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#585]
**Describe the bug**
The "Book a meeting" link under the DevHub homepage /get support Office hours section doesn't work. 

**To Reproduce**
1. Go to neardevhub.org
2. Scroll down to the /get support section and click "Book a meeting" under Office Hours
3. Takes you to an old page

**Expected behavior**
Please change "Book a meeting" text to "Join" and update the link to https://near.social/devhub.near/widget/app?page=community&handle=devrel&tab=Office%20hours%20/%20Support

**Comment by Megha-Dev-19** [comment]
hey @ori-near, on office hours page I don't see anything, is this broken.?

![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/dfae021d-a425-43a3-af94-29e61dacba8e)
