### ISSUE TITLE
Reply or edit a post doesn't close up editor after successful submit

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-bos#591]
Now when you reply a post, and successfully submit it, you'll still see the editor open, with the content you just wrote. And the cancel button doesn't work:
<img width="932" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/13259400/28fb54d5-d3fb-4b2c-bae3-7f07f25c2a66">

## Acceptance criteria
- [ ] successful reply post should not show the editor
- [ ] successful edit post should not show the editor
- [ ] cancel button on editor should close the editor
- [ ] add tests two ensure above requirements and avoid regression

**Comment by ailisp** [comment]
Overlap with #583 but we want to ensure tests to avoid regression

**Comment by elliotBraem** [comment]
@Megha-Dev-19 

For these tests, we can:

page.goto("/devhub.near/widget/app?page=feed&transactionHash=2123123123") which will represent a successful reply or edit -- if transactionHash present, confirm editor is detached.
