### ISSUE TITLE
Regression tests for critical use cases

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-bos#593]
We hit several regression bugs on post create, post reply, community edit etc. These are core functionality and critical use case of DevHub. We should ensure the correctness of them whenever we try to introduce new functionality, fix bugs or refactor.

## Acceptance criteria
Add playwright tests to:
- create every kinds of post
- reply every kinds of post
- create community
- edit community

For each of above operation, observe visually from playwright controlled browser window, and try to be as comprehensive as possible on assert the resulting behavior.  For example, before edit, the submit button should be disabled. After typing something, the submit button should be enabled and the cancel button should work. After success edit, the editor shouldn't appear. And whenever we hit a regression, we should complement these tests to prevent this bug happen again from any future changes.

**Comment by petersalomonsen** [comment]
First step, that I've looked into is to verify the resulting transaction contents of a post. I've started by extending the USDC test case, to resemble a funding request with the description field and tags filled. When user clicks submit, the transaction JSON is verified with the data filled into the post.

See ongoing work in https://github.com/NEAR-DevHub/neardevhub-bos/pull/607

**Comment by petersalomonsen** [comment]
I just added a test for the funding process as well: testing submitting a funding request, and receiving a sponsorship.

**Comment by petersalomonsen** [comment]
Also see a demo video here for the Github Codespaces and Playwright UI setup: https://youtu.be/urO50ZYvt-8

**Comment by petersalomonsen** [comment]
I have added tests for creating and editing communities in https://github.com/NEAR-DevHub/neardevhub-bos/pull/638

Also added some more documentation about the dev container setup and writing tests.
