### ISSUE TITLE
Tests should point to devhub.near, not devgovgigs.near

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/neardevhub-bos#594]
If you look through the current test suites, you'll notice that some of the tests still use the devgovgigs version of the app:

```
await page.goto(
    "/devgovgigs.near/widget/devhub.entity.addon.blog.Configurator?handle=devhub-test"
  );
```

All instances of this need to be updated to devhub.near

**Comment by elliotBraem** [comment]
This is blocked because:

The blog tests are configured with the addon deployed to [devgovgigs.near](https://near.org/devgovgigs.near/widget/devhub.entity.addon.blog.Configurator?handle=devhub-test)

They break when configured with the addon deployed to [devhub.near](https://near.org/devhub.near/widget/devhub.entity.addon.blog.Configurator?handle=devhub-test), as the blog selector does not show up.

Waiting for #561

**Comment by elliotBraem** [comment]
This is still waiting for #561

**Comment by Tguntenaar** [comment]
Closing this is not relevant anymore
