### ISSUE TITLE
As a user I want to submit while I preview my post

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#596]
### Problem

Right now if I edit a draft post and click on "preview" the submit button disappears.

### Steps to reproduce:

1. Go to [this page](https://near.social/devhub.near/widget/app?page=create)
2. Click on preview
3. See the submit button dissappear

### Solution:
It improve UI if I could submit while I'm previewing my draft post. As an example, Github does this with comments and issues.

**Comment by ori-near** [comment]
Thanks for filing this @Tguntenaar!

**Comment by itexpert120** [comment]
Let me fix this
