### ISSUE TITLE
Introduce Admin UI > Settings to allow admin to configure blog settings

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#599]
# Problem
Currently, our blog widget management page lacks a dedicate settings page to manage global blog configurations (e.g. title, display order, etc). Additionally, admins are required to use certain fields like the default Category with the three options (Guide, News, Reference). However, those categories were meant for the way that the DevDAO community wanted to customize their blogs – and they may need different categories or remove the altogether. We should not force admins to use a predefined setup or limits their ability to customize their blog's look and functionality.

This is a follow up issue to https://github.com/NEAR-DevHub/neardevhub-bos/issues/735, which introduces a new admin UI which includes a "Settings" button which will lead to the settings page configurations described in this issue.

# User Story
As a blog admin, I want a dedicated settings page so that I can easily configure settings based on my community's needs.

# Acceptance Criteria 
- [x] When an admin clicks "Settings" on the redesigned [blog dashboard](https://github.com/NEAR-DevHub/neardevhub-bos/issues/735), they see a dedicated Settings page. 
- [x] The settings page is divided into two sections with clear headings: "Blog List Page" and "Blog Post Fields"
- [x]  Blog List Page section allows the admin to configure:
  - [x] Blog title (displayed at the top of the page) 
  - [x] Blog subtitle (displayed below the title) 
  - [x] Enable/disable search functionality (https://github.com/NEAR-DevHub/neardevhub-bos/issues/733)
  - [x] Blog post sorting order (e.g. Newest to oldest, Oldest to newest, Alphabetical) – note this is based on published date)
  - [x] Number of posts displayed per page
- [x]  Blog Post Fields section allows the admin to configure:
  - [x] Categories
    - [x] Enable/disable category functionality for the blog. By the default they are disabled.
    - [x] Add/edit/delete up to 10 custom category options
    - [x] If community admin enables categories, they must add at least one category before saving. 
    - [x] Decide if to make this field required for every blog post
    - [x] When a user creates a new blog post within the selected widget, they see the categories field enabled with the categories that were set.
    - [x] If categories were not enabled, new blog post screen or any existing blog posts won't show the category field
    - [x] Once some posts contain categories:
      - [x] If community admin tries to delete that category or disable categories, there should be a warning saying all previous posts with that category will be removed (and then remove those categories from those posts)
      - [x] If community admin tries to edit that category, there should be a warning saying all previous posts with that category will be edit (and then edit those categories from those posts)
    - [x] Settings/categories should be unique to each blog widget.

Note: We may need to revisit what are the default configurations and if any are required. Whoever is working on this ticket should provide their recommendation and consult with the team/the product manager.

**Comment by Tguntenaar** [comment]
One extra feature that we added on our call is enabling and disabling showing the author on the blog.
