### ISSUE TITLE
Research SputnikDAO contract and configure it to fit treasury workflow

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-bos#622]
**Problem**
The Trustee dashboard and further proposal related workflow need smart contract support.

**User Story**
As a trustee, I want to act with a security-audited smart contract to approval proposal and release funding. 

**Acceptance Criteria**
- [x] Research the SputnikDAO contract and understand it's usage, feature and interface
- [x] Determine the feasibility and effort to use SputnikDAO contract for the treasury workflow. Either via configuration or slightly modification to the SputnikDAO contract. More specifically, treasury workflow includes:
  - [x] Moderator can submit a payment request, which references to a sponsorship post. The payment request amount, currency and receiver should match the sponsorship post.
  - [x] Moderators can manage an address book of receivers. Each receiver has a name, wallet address and two boolean property: KYC verified and test transaction sent.
  - [x] The payment request receiver must be in the address book and has KYC verified, test transaction sent.
  - [x] Trustees can view all payment requests sent by the moderators. 
  - [x] Trustees can pay the payment request, with the amount, currency and receiver specified in the payment request, from treasury wallet account.
  - [x] Trustees can view all transactions (payments to payment requests)
  - [x] Trustee can view the balance, staked amount and number of transactions of trustee wallet
- [ ] After research, create ticket to track configuration of the SputnikDAO contract to support the treasury workflow

**Reference Technical Design by @frol**

Trustees dashboard is a BOS-only project that should operate over a [SputnikDAO contract](https://github.com/near-daos/sputnik-dao-contract). We should deploy a security audited version of SputnikDAO contract to `treasury.devhub.near` and configure it in such a way that only trustees can act on proposals, but admins can add/remove trustees.

[DevHub Proposals](https://docs.google.com/document/d/15kYV36LP2Q-dWgb4eV8hxj7LZGwE5uCmnHojpntMy2Q/edit) will have a semi-automated way to `add_proposal` with an `ft_transfer` call with a specified amount of tokens from the treasury account to the proposal beneficiary specified in the proposal.

Trustees dashboard will be a simple interface over SputnikDAO contract where the list of pending actions for trustees will be just a [`get_proposals`](https://github.com/near-daos/sputnik-dao-contract/blob/2b19edb50e4542e1b8a6769023f2318c70255ee9/sputnikdao2/src/views.rs#L89) list and the “Pay” button calling [`act_proposal`](https://github.com/near-daos/sputnik-dao-contract/blob/2b19edb50e4542e1b8a6769023f2318c70255ee9/sputnikdao2/src/proposals.rs#L540C12-L540C24) (see [Astra++](https://near.org/astraplusplus.ndctools.near/widget/home?page=dao&daoId=auroradao.sputnik-dao.near) for the reference)

**Note**
- We'll eventually implement the way Frol proposed, but for the MVP, the DevHub Proposal Workflow is not yet exist. So we are using currently existing DevDAO sponsorship type of post, and add_proposal is still in the Sputnik DAO contract deployed at treasury.devhub.near. But the add_proposal is not automated, instead, it's called by DevHub moderators manually in the moderator dashboard. After DevHub Proposal Workflow is implemented, add_proposal can be automatically called when moderator approve a proposal.
- The "payment request" above is the naming for our product. It's corresponding to the "proposal" in SputnikDAO contract. The "proposal" in our product is the entire process of propose, comment, approve, request payment and payment, which is also different from "proposal" in SputnikDAO contract.

**Comment by Tguntenaar** [comment]
Update I planned a call with @ailisp tomorrow morning and will create the ticket, to track configuration of the SputnikDAO contract to support the treasury workflow, shortly after.

**Comment by Tguntenaar** [comment]
Also, I have deployed the sputnikn dao factory to `dhthomas.testnet` the dao to `treasury.dhthomas.testnet` and made an account `treasurythomas.testnet` to test sending tokens from the dao. @Megha-Dev-19 has been integrating it her front end.

**Comment by Tguntenaar** [comment]
I posted a new issue with the finding here: #636
