### ISSUE TITLE
Initialize routes for Proposal Flow

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/neardevhub-bos#630]
## Overview 

This is a technical story to lay the foundation for the new proposal flow. This must be completed first in order to allow parallel development of the pages. 

We will be introducing three new pages:
* Create Proposal
* View Proposal
* Proposal Feed

In app.js, create the following routes with corresponding page widgets:

- [x] proposal.create -> devhub.near/widget/page.proposal.create
- [x] proposal -> devhub.near/widget/page.proposal.index
- [x] proposal.feed -> devhub.near/widget/page.proposal.feed

## Acceptance Criteria

- [x] A new /proposals route is added to the Navigation bar, this should route to page=proposal.feed
- [x] User can navigate to create page via /devhub.near/widget/app?page=proposal.create
- [x] User can navigate to view page via /devhub.near/widget/app?page=proposal
- [x] User can navigate to feed page via /devhub.near/widget/app?page=proposal.feed

## Test Coverage

(we are initializing the test suites for each page)

- [x] Clicking the /proposals in navbar redirects to /devhub.near/widget/app?page=proposal.feed
- [x] page.goto devhub.near/widget/page.proposal.create renders create proposal page
- [x] page.goto  devhub.near/widget/page.proposal.index renders proposal page
- [x] page.goto  devhub.near/widget/page.proposal.feed renders proposal feed page

**Comment by Tguntenaar** [comment]
I suppose the proposal flow issues should be merged to develop instead of main, but only after announcments / discussions is fixed.

**Comment by Tguntenaar** [comment]
I'm dropping this back to the backlog in favour of implementing discussions first

**Comment by Tguntenaar** [comment]
Closing this issue since it is not necessary anymore
