### ISSUE TITLE
"Proposal Feed" Page - Front End

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/neardevhub-bos#634]
## Overview 

This is the front end story for implementing the "Proposals Feed" page. This story is dedicated to implementing the layout, core structure, and behaviors. This should be done in parallel with the components being created. This prioritizes functionality in order to enable the back end stories.

**Note**: We have a lot of different implementations of feeds in devhub... this is an opportunity to create a good, flexible version that can then replace the others. 

![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/16282460/de86424c-9b5b-4f86-a578-012ed7d32942)

## Acceptance Criteria

1) Page should match Figma
2) Parent manages state from the panel and passes to the Feed
3) Optional: Panel is flexible in that the left and right elements are defined in the parent

Source is TBD, may be devhub contract or posts

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – is this ticket still in progress? Or do we need to make any updates?
