### ISSUE TITLE
Introduce promoted posts

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#65]
**Problem**
Out platform currently does not offer a way for users to promote their posts in order to gain more visibility. As a result, users who want to draw more attention to their ideas have to rely on their own promotion and marketing efforts.

**User Story**
As a Gigs Board user, I want to have the ability to promote my posts to increase their visibility on the platform and reach a wider audience.  

**Acceptance Criteria**
- Display promoted posts as compressed form at the top of the homepage (either in the feed or in a dedicated section)
- Post authors should have the ability to bid with NEAR to get their posts displayed
  - One can set intervals for each bid, which would spread the money evenly, i.e. a bid of 100 NEAR over 10 days has the same power as a bid of 10 NEAR for 1 day if their schedules overlap. 
- Three posts with the highest bid should display at the top
- Randomize the display of posts with equal bids
- There is a link to show all promoted posts
- Proceeds should be immediately transferred to the NEAR Dev Gov account

**Note**
- This idea was featured as a bounty at the [ETH Denver Hackathon](https://www.ethdenver.com)

**Comment by ailisp** [comment]
Is this still relevant? This was partially implemented by a team in ETH Denver Hackathon, we can still find and try to integrate it to new DevHub app. And definitely need a design matches to current DevHub app if we still want this.

**Comment by ori-near** [comment]
Let's hold on this for now. We have a few other higher priority features, will update the backlog today.
