### ISSUE TITLE
NEAR Campus community admin is unable to create more than 13 blog posts

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#653]
**Describe the bug**
I received a report from Ester F that she is unable to create additional blog entries for the NEAR Campus community. She is using the Blog Widget for the "[Universities](**url**)" tab. Currently there are 13 entries. When she tries to create a new post, and clicks the confirmation/payment screen, the new post is not published or created.

**To Reproduce**
1. Go to https://near.social/devhub.near/widget/app?page=community&handle=near-campus&tab=universities as a page admin
2. Click on Settings
3. Enter all fields
4. Click publish and confirm transaction.
5. Don't see new post

**Expected behavior**
Community admin should be able to create additional posts.

**Comment by Tguntenaar** [comment]
This issue does no longer exist with blog v2
