### ISSUE TITLE
Leaving a comment to announcement post makes an empty comment

### ISSUE THREAD

**Issue by frol** [NEAR-DevHub/neardevhub-bos#662]
**Describe the bug**

I tried commenting on an announcement post from DevHub Community page and my comment is displayed as empty on near.org feed:

<img width="947" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/304265/a20bec3f-88bf-423d-ada4-15df95e2e740">

https://near.org/near/widget/ProfilePage?accountId=hot-ideas.community.devhub.near

It gets displayed on near.social just fine:

https://near.org/mob.near/widget/ProfilePage?accountId=hot-ideas.community.devhub.near

**To Reproduce**

1. Go to DevHub community with an announcement
2. Leave a comment to any of the announcements
3. See the empty comment

**Expected behavior**

The comment should be displayed normally.

<img width="914" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/304265/ecc11dc6-d40e-43a7-8117-c7461cb2280b">

**Comment by petersalomonsen** [comment]
It seems to me that when leaving a comment, you need to reload the page to actually see it. Happened both times for the comments here:

https://near.org/near/widget/ProfilePage?accountId=webassemblymusic.community.devhub.near&transactionHashes=FebHf1H1CAGhjWAmthkNRN5YGXgKpkNdcGjxaAqfwjuv

**Comment by frol** [comment]
@petersalomonsen I was refreshing the page and even went to the profile feed (gateway native Profile Page), and the comment was empty up until maybe 10 minutes later.

**Comment by petersalomonsen** [comment]
> @petersalomonsen I was refreshing the page and even went to the profile feed (gateway native Profile Page), and the comment was empty up until maybe 10 minutes later.

@frol For me, just one refresh was needed, I did not have to wait. The 10 minute delay you experienced, and that I also observed on your particular post, must have been a glitch then.

But still, refreshing should not be needed either, and seems reproducible, so I could look into that particular issue.

**Comment by frol** [comment]
I think it is a bug on the indexing side, there is nothing we can do about it, so I’m closing this issue
