### ISSUE TITLE
Migrate v1 blogs to v2

### ISSUE THREAD

**Issue by ailisp** [NEAR-DevHub/neardevhub-bos#664]
Now each community has its community account that we can store community owned data in SocialDB. We have it to store announcements. I propose to migrate the blog system to store in community SocialDB because it would be not hacking post with json content to store blogs, require no migration, and can utilize the NearSocial's index api (not QueryAPI) to list blog feed and will not have issues like https://github.com/NEAR-DevHub/neardevhub-bos/issues/653.

### Acceptance Criteria
- [x] Add `add_blog`/`edit_blog` method in devhub contract, which check if the caller is community admin, and save blog post in community's SocialDB
- [x] replace the create and edit blog with `add_blog` and `edit_blog` on frontend
- [x] list blogs with `Social.index`
- [x] Migrating existing blog posts to SocialDB

**Comment by ailisp** [comment]
As a follow up to this ticket, We can reuse the widget by core experience team: https://github.com/near/near-discovery/issues/943

**Comment by frol** [comment]
@ailisp As we discussed it over our 1:1, we can build blogs similar to the how widgets are stored in SocialDB. Let's do that.

**Comment by ori-near** [comment]
@frol @Tguntenaar @petersalomonsen Is this ticket still relevant?

**Comment by petersalomonsen** [comment]
I guess not, since we now have the new blog feature going on. @ori-near

**Comment by Tguntenaar** [comment]
@petersalomonsen @ori-near Yes it is still relevant. The new blog feature is only there so the two versions could live next to eachother without needing to migrate first. 

We can migrate all blogs over to the new addon and sunset the old addon.

**Comment by petersalomonsen** [comment]
> @petersalomonsen @ori-near Yes it is still relevant. The new blog feature is only there so the two versions could live next to eachother without needing to migrate first.
> 
> We can migrate all blogs over to the new addon and sunset the old addon.

So we want to migrate blogs to the new addon if I understand correct? We don't want to migrate the old blog to SocialDB? So this issue should be rephrased to something like "Migrate v1 blogs to v2"?

**Comment by Tguntenaar** [comment]
We can definitely rephrase it. Essentially, we're migrating from our current blog posts in the devhub.near contract to socialdb.

**Comment by Tguntenaar** [comment]
@petersalomonsen I made a [script](https://github.com/Tguntenaar/migrate-devhub-blogs) to upload the blogs to the new blog addon. However only a devhub moderator is able to execute it for all communities.

The blog-v2 branch has to merge first, bc the first blog addon instance of every community will have a default id in order to make this migration possible. 

See https://github.com/Tguntenaar/neardevhub-widgets/blob/f0e123763693526f169494e0922169b8e30323ed/src/devhub/entity/community/configuration/AddonsConfigurator.jsx#L212

**Comment by petersalomonsen** [comment]
> @petersalomonsen I made a [script](https://github.com/Tguntenaar/migrate-devhub-blogs) to upload the blogs to the new blog addon. However only a devhub moderator is able to execute it for all communities.
> 
> The blog-v2 branch has to merge first, bc the first blog addon instance of every community will have a default id in order to make this migration possible.
> 
> See https://github.com/Tguntenaar/neardevhub-widgets/blob/f0e123763693526f169494e0922169b8e30323ed/src/devhub/entity/community/configuration/AddonsConfigurator.jsx#L212

OK, let me know when we should run this script then.

**Comment by Tguntenaar** [comment]
This issue is blocked by PR #761

**Comment by Tguntenaar** [comment]
Did the migration last week with @petersalomonsen
