### ISSUE TITLE
Missing blog entries

### ISSUE THREAD

**Issue by MaksymZavershynskyi** [NEAR-DevHub/neardevhub-bos#667]
**Describe the bug**
Blog post https://near.social/devhub.near/widget/app?page=blog&id=3034 is missing from https://near.social/devhub.near/widget/app?page=blog 
**Expected behavior**
https://near.social/devhub.near/widget/app?page=blog  lists all blog posts in chronological order.

**Comment by ailisp** [comment]
@MaksymZavershynskyi Hi Max, thanks for reporting! This is expected behavior as https://near.social/devhub.near/widget/app?page=blog only shows all blogs for developer-dao community. The blog post you reported is from devrel community.
