### ISSUE TITLE
Error while creating community

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-bos#669]
<img width="365" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/69b74d49-33f5-470f-87b8-d6c372245631">

**Comment by ailisp** [comment]
@Tguntenaar Have we update frontend to deposit 4 NEAR?

**Comment by ailisp** [comment]
Fixed in #673
