### ISSUE TITLE
Posts are missing from the activity feed

### ISSUE THREAD

**Issue by PiVortex** [NEAR-DevHub/neardevhub-bos#671]
**Describe the bug**
Not all posts are showing in the activity feed for me.

Take this [proposal](https://near.social/devhub.near/widget/app?page=post&id=2968) I did not know that this proposal existed until it was sent to me. I am unsure whether there are a lot more posts missing since I cannot see them 

**To Reproduce**
For the given example look at the date and id of the post, scroll down in the feed to where the post should reside, it does not appear.

**Expected behaviour**
All posts should appear in the activity feed.

An exceptional fix of this bug will make me or another DevRel contributor aware of all the posts that were missing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome

**Comment by ailisp** [comment]
This post is a comment instead of a top level post. To see the comment, select "Sort: all replies" and you'll see it:

<img width="1296" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/13259400/c6842224-917a-4eef-a0b9-f9ced6369132">

**Comment by PiVortex** [comment]
Ahh, I see. Thank you!
