### ISSUE TITLE
Callback support to set method in social-db

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#681]
This is actually a feature request for social-db but has effect on devhub. This ticket is used to track the progress on our board.

### **Is your feature request related to a problem? Please describe.**
A community discussion post works as follows: 
1. a users posts to his/her social-db account 
2. the discussions account (`discussions.${handle}.community.devhub.near`) than reposts the users post using the blockheight.

Right now we match content of the latest social-db post before reposting to a `discussions.${handle}.community.devhub.near` account. This is done in order to wait for the correct blockheight. 

### **Describe the solution you'd like**

A better fix would be to introduce a callback support to set method implementation of SocialDB, so calling set we can ask it to call devhub.near contract passing the block height and the keys that were updated (`frol.near/post/main`)

### **Describe alternatives you've considered**
The alternative is what is implemented now via this PR: https://github.com/NEAR-DevHub/neardevhub-bos/pull/670

### **Additional context**
See these discussions on telegram from more context: 
1. https://t.me/c/1822948693/5050/5185
2. https://t.me/NearSocialDev/5882

**Comment by Tguntenaar** [comment]
Update: I authored the draft on social-db here: https://github.com/NearSocial/social-db/pull/18

**Comment by ori-near** [comment]
@Tguntenaar @frol Is this ticket still relevant?

**Comment by Tguntenaar** [comment]
This ticket has become irrelevant to our developments.
