### ISSUE TITLE
Cannot scroll down far on the activity feed, not all posts are loading 

### ISSUE THREAD

**Issue by PiVortex** [NEAR-DevHub/neardevhub-bos#684]
**Describe the bug**
I cannot scroll down very far on the activity feed. I can see the first 6 posts but the others will not load after that.

**To Reproduce**
Go to the activity feed https://near.social/devhub.near/widget/app?page=feed, scroll down, and see if later posts load. 

**Expected behavior**
All posts in the activity feed should load when scrolling down.

**Screenshots**
![image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/124691791/01b0530e-0928-4a76-9236-a223fb6f1b54)
Continues to show "loading"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

If you can reproduce this error please make it high priority as this is stopping me from assessing past proposals.

**Comment by flmel** [comment]
![bug6](https://github.com/NEAR-DevHub/neardevhub-bos/assets/55487633/21b592f9-5f44-412b-98c0-f8aee33a96e0)

Desktop (please complete the following information):
    OS: OSX Sonoma
    Browser Firefox

**Comment by frol** [comment]
@ailisp Could you, please, check the indexer?

**Comment by ailisp** [comment]
Looks it's a frontend issue. Posts are correctly loaded in console log:

<img width="1545" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/13259400/cc72cc8a-8d8f-4605-b89f-4c7f2a7cfb1f">

**Comment by ailisp** [comment]
I found if revert this PR:
https://github.com/NEAR-DevHub/neardevhub-bos/commit/5ff64c3b529484ee4b959507783183046cb56bde#diff-f3bbd436e63cc7815c7ce670120d6c94070862a24ea90e8191fdca47e65a4014

(this is the previous commit before this PR: `git checkout 41693a9dbe6a9cdebfb1a92ef10eb32bc343edce`)

the loading works without problem. Although the change looks irrelevant. @Megha-Dev-19 Can you take a look on why it cause the problem? If we can't figure out it in a day, let's revert this PR.
