### ISSUE TITLE
Creating a discussion not working after RPC breaking change

### ISSUE THREAD

**Issue by petersalomonsen** [NEAR-DevHub/neardevhub-bos#695]
**Describe the bug**
Creating a discussion involves looking up a transaction by its hash. Because of a [breaking change in the RPC API](https://github.com/near/docs/commit/fcb2f1138329774383070ceb00d3289e69ac779f#diff-5c9629a0ee653d5b9dfb5a368224d52a73de7c73600584bed34328357cc8db27R258) this does not work anymore.

**To Reproduce**
This is reproduced by the discussions test case ["should create a discussion when content matches"](https://github.com/NEAR-DevHub/neardevhub-bos/blob/main/playwright-tests/tests/discussions.spec.js#L8)

**Expected behavior**
It should be able to find the transaction in the transaction hash.

**Comment by petersalomonsen** [comment]
The breaking change seem to have been introduced here

https://github.com/near/nearcore/pull/9648

**Comment by frol** [comment]
There was a bug in read-rpc that did not implement the backwards compatibility for the `tx` API change. It was fixed yesterday: https://github.com/near/read-rpc/issues/212

If this issue still persists, let's re-open this ticket.
