### ISSUE TITLE
Proposals: Add autolinked references to existing proposals

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#710]
**Problem**
As a user, I want to sometimes reference other proposals in my comments. However, right now I don't have a way to easily find them, forcing me to manually look for their URL and paste them in. Unfortunately this takes extra time and doesn't look very good.
![Screenshot 2024-03-25 at 3 16 48 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/0d993575-574b-4e8d-adb3-19b5d5794ff2)

**User Story**
As a user commenting on DevHub proposals, I'd like to easily reference other proposals in my comment so that I can save time and make my references easy to digest.

**Acceptance Criteria**
- [ ] When a user is writing a comment, if they type "#" they should see a dropdown list of proposals (similar to the link proposals feature) that allows them to see recent proposals or search for one by ID
- [ ] When a user selects a proposal such as 13, they will see `#13` in the write mode. But in the preview mode, it will render as "Proposal Title `#13`" and that entire line becomes a hyperlink to the proposal.

**Comment by Megha-Dev-19** [comment]
Blocked by #725, will add it after the dropdown is added, since it has similar UI implementation

**Comment by Megha-Dev-19** [comment]
hey @ori-near could you please check the [preview](https://near.org/megha19.near/widget/app?page=create-proposal)
For having separate text in preview and write mode it's pretty complicated, not sure if it's even possible, will this version work for now?

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – the preview looks great. As we discussed last week, it would be awesome if we could also show the preview to a referenced proposal when the URL is entered directly. For example, if I type "https://near.social/devhub.near/widget/app?page=proposal&id=62" – I should see both instances show up like the second line in the attached image (# proposal title):

![Screenshot 2024-04-29 at 1 17 13 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/42d6c527-e948-48ba-890e-26088db2b77e)
