### ISSUE TITLE
Implement search and category filter within the blog widget

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#733]
# Problem
Currently, the blog widget lacks search functionality and the ability to filter content by categories. Since we plan to add more content in the coming weeks, it will become increasingly difficult for users to find and filter specific content.

# User Story
As a blog reader, I want to have the ability to search and filter for blog posts (if enabled by the admin in https://github.com/NEAR-DevHub/neardevhub-bos/issues/599) so that I can easily search for specific content.

# Acceptance Criteria

Search functionality
- [x] When search is enabled by the admin in the [settings](https://github.com/NEAR-DevHub/neardevhub-bos/issues/599), a search bar should appear at the top of the blog widget
- [x] Users can enter key words to search for content within the specific blog post for that widget
- [x] Search results should dynamically filter displayed posts based on the entered keywords in the search bar

Category Filtering
- [x] If category functionality is enabled by the admin in the [settings](https://github.com/NEAR-DevHub/neardevhub-bos/issues/599), a category filter dropdown should appear next to eh search bar.
- [x] The dropdown should list all the available categories for the blog. 
- [x] If a user selects a category, that should dynamically filter the post list to only show posts with that category
- [x] Users can combine search key words and category filters to refine their search results.

Scope: Search results should be limited to posts within the specific blog widget. We can explore expanding search to all communities blog posts in another ticket later.

**Comment by petersalomonsen** [comment]
@Tguntenaar As you can see in #772 I've implemented search functionality, but I think the posts does not have a category yet, so unable to proceed with category filtering. Is it so that there will be a category field in the metadata?

**Comment by Tguntenaar** [comment]
Closing this issue, since it is already merged.
