### ISSUE TITLE
RFP Create/Edit

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#747]
# User Story
As an Infrastructure Committee Admin, I want to have a way to create and edit RFPs so that I can sponsor and facilitate community involvement in infrastructure related work.

# Acceptance Criteria
- [x] Verify that the UI implementation corresponds to the Figma design
- [x] Once an admin clicks “Create RFP” from the RFP Feed screen, they see the create form, which has some similarities (but a few differences) to the DevHub [proposal form](https://github.com/NEAR-DevHub/neardevhub-bos/issues/633)
- [x] Admin is able to add/edit the following fields (* indicates optional field)
  - [x] Category Dropdown (Bridges, Data Lakes, Explorers, Onramps / Offramps, Oracles, Query API, ~Wallets~, Other)
    - [x] Admin is able to select multiple categories. We should treat this field more like labels.
    - [ ] If an admin edits categories for an RFP, any associated linked proposals will automatically get updated (with a log showing in their proposal).
  - [x] Title
  - [x] Summary
  - [x] Description
  - [x] Final consent checkboxes
  - [x] Submission Deadline
  - [ ] Timeline Stage
    - [ ] For Decision Stage: 
      - [x] If admin selects Decision Stage in the dropdown, they must click “Proposal Selected” or “RFP Canceled” radio button.
      - [ ] Admin cannot choose “Proposal Selected” if the Selected Proposal section below is empty. If they try to click “Proposal Selected” they should see a warning message.
  - [ ] *Selected Proposal: Only show approved proposals in dropdown. If no approved proposals, show warning message “There are currently no approved proposals”.
- [ ] **Buttons:** Admin should see 3 buttons at the bottom of the form:
  - [ ] **Cancel RFP:** (This will only show in edit once RFP was created) Clicking on it will show the “Confirm proposal cancellation” pop up, see https://github.com/NEAR-DevHub/neardevhub-bos/issues/778 for details. Upon confirmation, the proposal will move to the RFP Cancelled stage. 
  - [x] **Discard Changes:** Clicking on it will cancel without saving changes.
  - [x] **Submit:** Clicking on it will publish/save the RFP.

# Attachments

See mock up:
![create](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/17a0567e-7f81-4583-b4c7-347dddac7449)

**Comment by Megha-Dev-19** [comment]
Here is the [PR](https://github.com/NEAR-DevHub/near-prpsls-bos/pull/3)

**Comment by Megha-Dev-19** [comment]
hey @ori-near, can you please design the cancel RFP modal that we discussed, one with cancel selected/all linked proposal or unlink them.

**Comment by ori-near** [comment]
> hey @ori-near, can you please design the cancel RFP modal that we discussed, one with cancel selected/all linked proposal or unlink them.

Hi @Megha-Dev-19 / @PolyProgrammist  – created a separate ticket for this: https://github.com/NEAR-DevHub/neardevhub-bos/issues/778. Let me know if you have any questions.

Also please note I updated the categories list in the AC (e.g. removed Wallets)

**Comment by Megha-Dev-19** [comment]
hey @ori-near, can you please share the warning message for this `Admin cannot choose “Proposal Selected” if the Selected Proposal section below is empty. If they try to click “Proposal Selected” they should see a warning message.`
