### ISSUE TITLE
Events Committee Proposal Portal

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#767]
This ticket is to set up a DevHub instance of the proposal management feature for the Events Committee. This would enable them to sponsor initiatives similar to DevDAO.

# User Story

- [x] As a user, I want to discover the latest list of proposals to the Events Committee so that I can learn about the latest proposed solutions and their statuses.
- [x] As an individual or team who wants to contribute to NEAR events, I want to have a way to submit a proposal

# Acceptance Criteria

- [ ] There is a new Events Committee Proposal portal with these tabs: Proposals, About, Admin (Only admins can see this)
- [ ] Replace the existing DevHub logo with the new Events Committee logo

## Proposals
- [ ] Feed shows a banner message at the top of the feed with instructions specific to the Events Committee for message on top of the feed
- [ ] Feed shows all of the latest proposals and their statuses
- [ ] Users can search and filter through the proposals
- [ ] All users can click Submit Proposal to create new proposals
  - [ ] Not logged in users will get redirected to a “Not Logged In” screen similar to DevHub proposals
- [ ] Each proposal card displays relevant information, including:
  - [ ] Profile picture of proposal author 
  - [ ] Proposal title
  - [ ] Linked proposal (if proposal is linked to a specific RFP)
  - [ ] Categories (allow multiple, treat similar to labels)
  - [ ] Author name (with link to profile) and created date
  - [ ] # of likes
  - [ ] # of comments
  - [ ] Proposal status
- [ ] Load more allows to see additional proposals beyond the most recent ones

## Admin
- [ ] Only admins will see an Admin link in the website navigation, visible and accessible only to Events Committee admins
- [ ] When an admin clicks on the Admin button, they see a moderators tab that allow them to view and edit members
- [ ] Clicking edit members will allow admins to remove or add existing members
- [ ] Any users with admin permissions will have permissions to edit/manage proposals and manage admins.

## About
- [ ] We display the attached copy on the page

# Assets

1. Attached Mockup

![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/26429b86-575d-44b5-90e4-9f2782641d6c)

2. Events Committee Logo (All pages)

Attached logo (white):
![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/d42cc3a4-5f8a-48ac-99d7-1eaf2f922a83)

3. Proposal Feed Banner Copy
`Welcome to the Events Committee Proposal Feed! This dedicated space makes it easy to submit and track funding proposals from the Events Committee, the cross-team organization responsible for hosting and sponsoring developer-focused events. You are welcome to respond to any RFPs that are accepting submissions or submit an independent proposal.`

4. Proposal Categories
- Bounty
- Bounty booster
- Event sponsorship
- Events team
- Hackathon
- Hackbox
- Meetup
- Travel expenses

![Image](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/d21c9520-086b-461c-97ab-0bbf28707eb1)

5. About Page Copy
See [copy](https://docs.google.com/document/d/1sQbB2XahLXskbWPgZ06UPiPvx0t46-pCDM3eSwaEP8c/edit?usp=sharing)

6. List of admins
Maria, Ori, Vlad for now

**Comment by Tguntenaar** [comment]
5. List of admins

**Comment by Tguntenaar** [comment]
Done
