### ISSUE TITLE
Add account autocomplete input for admin configuration

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-bos#783]
1) Admins can visit the [admin page](https://near.org/devhub.near/widget/app?page=admin)
2) When you enter the account ID, we should have the suggestion roll, for better UX
<img width="1202" alt="image" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/100185149/ce9e5117-e6b9-463a-83d7-81dc94969999">

Instances to check
- [x]  Devhub proposals
- [x]  Infrastructure committee
- [ ]  Events committee

**Comment by ori-near** [comment]
@Megha-Dev-19 Is this ticket not complete?
