### ISSUE TITLE
View Proposal - Linked RFP or Linked Proposals should reference user's current gateway session

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#811]
**Affected Portal:**
`IMPORTANT` All Portals

**Description:**
Currently, when a user links another proposal to a proposal (or links RFP to proposal in the case of the Infrastructure Committee), the linked URL always references the near.org gateway instead of the user's gateway in the current session. This can lead to confusion – because if a user supposedly uses the near social gateway and clicks on that link, it will take them to a version of the portal where they are not logged in. Which creates a jarring experience.

**User Type:**
Logged in users

**Reproduction Steps**
1. Make sure you are signed out of near.org gateway
2. Go to near social gateway and log in
3. Create and publish an Infrastructure Committee proposal with a linked proposal or a linked RFP (e.g. such as https://near.social/megha19.near/widget/near-prpsls-bos.components.pages.app?page=proposal&id=6) or a DevHub proposal with linked proposal (e.g. https://near.social/devhub.near/widget/app?page=create-proposal&id=86)
4. Try to click on the associated links for proposal OR RFP and see that they take you away from near social gateway to near.org gateway where you are logged out

**Expected behavior**
Any linked proposals or RFP should stay within the gateway the user is logged into. So the URL should point to the part after near.org or near.social ...

**Priority**
Low (P3) – Minor inconvenience

**Environment Details**
N/A

**Comment by Megha-Dev-19** [comment]
We still need to update:
- [ ] Devhub
- [ ] Events committee
