### ISSUE TITLE
Community announcements share link url leading to 404 error

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#846]
**Affected Portal:**
DevHub

**Description:**
I am unable to share links to announcements within DevHub communities on any gateway

**User Type:**
Regular user

**Reproduction Steps**
1. Go to [DevHub Platform Community](https://near.social/devhub.near/widget/app?page=community&handle=devhub-platform&tab=announcements)
2. Click the copy URL to clipboard icon for the first post
3. Open the URL
4. See 404 | This page could not be found.

**Expected behavior**
Clicking on the URL should open the correct post

**Visual Reference**
![Screenshot 2024-06-20 at 4 00 31 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/3a85d366-9af5-40f8-bb41-dfa4aba1ec00)

**Priority**
P2

**Environment Details**
- Device: Desktop
- OS: Mac
- Browser: Safari
- Version: Version 17.3.1 (19617.2.4.11.12)

**Comment by Tguntenaar** [comment]
It seems that the near.org path to individual posts has been removed all together. Copying the link to posts on my profile is also broken.

**Comment by Tguntenaar** [comment]
Fixed!
