### ISSUE TITLE
Move KYC/KYB proposal timeline step from Payment Processing to Review stage

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#848]
# Background
We require KYC/KYB verification in order to issue payments to recipients. Currently, this steps occurs after proposal decision, which can lead to delays or problems if the recipient fails verification (e.g. hackathon winner is from a sanctioned country and therefore can't get paid).  To solve this, we want to move the KYC/KYB from the Payment Processing to the Review stage, to ensure the recipient is verified prior to the decision.

# User Story
As a moderator (e.g. proposal approver), I want to verify recipient KYC/KYB information during the Review Stage so I can approve proposals with confidence that the payments will proceed smoothly. 

# Acceptance Criteria
- [x] Move the the "Sponsor verifies KYC/KYB" checkbox from the Payment Processing stage to the Review Stage
- [x] Make the "Sponsor verifies KYC/KYB" checkbox mandatory to proceed from Review to Decision stage
- [x] When author selects the "Sponsor verifies KYC/KYB" checkbox and clicking save, log the action explicitly in the proposal history log
- [x] If an admin resets a proposal from a later stage (e.g. Funded or Payment Processing) back to Draft, the  "Sponsor verifies KYC/KYB" checkbox should be cleared.

‼️ Note: None of these changes will affect the actual Recipient Verification Status behavior or logic. Just the timeline and how admins interact with them.

# Screenshots

## Current State
![Screenshot 2024-06-20 at 4 40 19 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/d2d69b35-35aa-4ebb-a3f2-8bacef4039bb)

## Desired State
![Screenshot 2024-06-20 at 4 40 58 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/9ae27d10-a65e-48bc-bdbc-a61a320db4cb)

**Comment by Megha-Dev-19** [comment]
@ori-near you said `Make the "Sponsor verifies KYC/KYB" checkbox mandatory to proceed from Review to Decision stage`, but what if moderator wants to "Cancel" or "Reject" it, in that case "KYC verification" is not necessary right?

**Comment by ori-near** [comment]
@Megha-Dev-19 – correct, cancel or reject should not depend on KYC/KYB verification.

**Comment by PolyProgrammist** [comment]
As we discussed with Megha in DM, need to keep kyc in payment processing stage for infrastructure-committee.near. For events and devhub add to review

**Comment by Megha-Dev-19** [comment]
Need to be done for events

**Comment by Megha-Dev-19** [comment]
Needs to be added for events-committee.
