### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Tguntenaar** [NEAR-DevHub/neardevhub-bos#852]
I received this github security alert. 

![IMAGE 2024-06-21 15:26:57](https://github.com/NEAR-DevHub/neardevhub-bos/assets/28901891/b55a5787-1325-4db7-b9f5-714ebbed5e2c)

**Comment by Tguntenaar** [comment]
<img width="1042" alt="Screenshot 2024-06-21 at 15 47 27" src="https://github.com/NEAR-DevHub/neardevhub-bos/assets/28901891/8672fb0c-1356-4690-bd43-ba582ecd3add">

**Comment by ori-near** [comment]
Hi @Tguntenaar – is this ticket actionable and still relevant? If so, can you please add more details or let me know if we should close it?

**Comment by Tguntenaar** [comment]
@ori-near I will quickly audit this and see if it is still relevant. All dependencies these vulnerabilities are indirect dependencies so we might not be able to update some of them.
