### ISSUE TITLE
Use "Load More" instead of infinite scroll for proposals feed

### ISSUE THREAD

**Issue by Megha-Dev-19** [NEAR-DevHub/neardevhub-bos#855]
Currently because of absolute positioning, in [proposal feed](https://near.social/devhub.near/widget/app?page=proposals), it fetches all proposal at once, and since now we have good number of proposals, it takes some time to load them all.
@ori-near what do you think? should we move to  "Load More" to optimise the UX.

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – yes please! Let's do it.
