### ISSUE TITLE
Feed status isn't matching with proposal status

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#870]
**Affected Portal:**
DevHub (maybe others too?)

**Description:**
It seems like there's a mismatch in the proposal status shown in the feed vs the proposal view page. For example, for proposal 72, the feed shows payment processing:
![Screenshot 2024-07-10 at 2 35 21 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/f31e861c-79c6-42f0-b11c-7dff2520fd41)

But the proposal is actually in the funded stage:
![Screenshot 2024-07-10 at 2 35 46 PM](https://github.com/NEAR-DevHub/neardevhub-bos/assets/110252255/5977086b-6887-4a62-a4c3-dd7ebcc3ed97)

**User Type:**
Regular Users

**Reproduction Steps**
1. I recently updated (as an admin) the status of this proposal to funded.
2. Now when I visit the feed, status still says Payment Processing but proposal says Funded.

**Expected behavior**
Status should be accurate on feed.

**Priority**
High (P1) – Unexpected error or behavior

**Comment by Megha-Dev-19** [comment]
The indexer was fixed by @PolyProgrammist.
