### ISSUE TITLE
Fractal verification failing to get status

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#966]
**Affected Portal:**
All

**Description:**
Currently, Fractal verification is not loading for recipients.

**User Type:**
All

**Reproduction Steps**
1.  Open any proposal on any portal 
2. View Recipient Verification Status section on right sidebar
3. See "Failed to get status"

**Expected behavior**
Fractal verification should pull from our KYC database.

**Visual Reference**
![Image](https://github.com/user-attachments/assets/ee794fea-e96c-4e04-a6f2-6671b2a25f7c)

**Priority**
High (P1) – Unexpected error or behavior

**Comment by ori-near** [comment]
Note: This is not critical, as we still have a way to check in the backend if users are verified. But moderators should verify with our FinOps that the recipient is verified before approving any proposals.

**Comment by Megha-Dev-19** [comment]
It's fixed, @frol reran the service and it works fine now.
