### ISSUE TITLE
Split PR 982 up per feature

### ISSUE THREAD

**Issue by ori-near** [NEAR-DevHub/neardevhub-bos#996]
We will split up PR #982 into smaller PR's so we can review it more easily.

The features per portal are: 
- Devhub.near
- [x] #999
- [x] #1000
- [x] #1001
  - Accepted Terms and Conditions
  - Editor.jsx
- [x] #1002
- Events Committee ( uses mostly the same components as Devhub. in PR #982 I removed the dropdown and simple MDE to use DevHub's. So these issues are the same as for Devhub.
- [x] #1002
- [x] #999 
- [x] #1000
- Infrstructure Committee
- [x] #1009
- [x] #1010
- [x] #1011
- [x] #1012

**Comment by Tguntenaar** [comment]
The remaining task is to split the infrastructure committee features into individual issues. This will allow us to track progress and close them with separate PRs.
